#!/bin/sh
# build reZet80 SCOUT
cd src
# compile with z80asm v1.8
z80asm _scout.asm -o ../rom/_scout.z80 --list=../rom/_scout.lst
cd ..
# program 2 KiB UVEPROM
#minipro -v -p m2716@dip24 -w rom/_scout.z80
# program 2 KiB EEPROM
#minipro -v -p cat28c16a -w rom/_scout.z80
# program 4 KiB UVEPROM
#minipro -v -p m2732@dip24 -w rom/_scout.z80
